/*
 * Timmi Absences API
 * Welcome on the documentation for Timmi Absences API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developers@lucca.fr
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ImportsCreateAbsencesBatchResponse
 */
public class ImportsCreateAbsencesBatchResponseTest {
    private final ImportsCreateAbsencesBatchResponse model = new ImportsCreateAbsencesBatchResponse();

    /**
     * Model tests for ImportsCreateAbsencesBatchResponse
     */
    @Test
    public void testImportsCreateAbsencesBatchResponse() {
        // TODO: test ImportsCreateAbsencesBatchResponse
    }

    /**
     * Test the property 'summaryId'
     */
    @Test
    public void summaryIdTest() {
        // TODO: test summaryId
    }

    /**
     * Test the property 'hasError'
     */
    @Test
    public void hasErrorTest() {
        // TODO: test hasError
    }

}
