/*
 * Timmi Absences API
 * Welcome on the documentation for Timmi Absences API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developers@lucca.fr
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ImportsEntitlementsBatchImportResponse
 */
public class ImportsEntitlementsBatchImportResponseTest {
    private final ImportsEntitlementsBatchImportResponse model = new ImportsEntitlementsBatchImportResponse();

    /**
     * Model tests for ImportsEntitlementsBatchImportResponse
     */
    @Test
    public void testImportsEntitlementsBatchImportResponse() {
        // TODO: test ImportsEntitlementsBatchImportResponse
    }

    /**
     * Test the property 'successLinesCount'
     */
    @Test
    public void successLinesCountTest() {
        // TODO: test successLinesCount
    }

    /**
     * Test the property 'globalErrors'
     */
    @Test
    public void globalErrorsTest() {
        // TODO: test globalErrors
    }

    /**
     * Test the property 'lineErrors'
     */
    @Test
    public void lineErrorsTest() {
        // TODO: test lineErrors
    }

}
