/*
 * Timmi Absences API
 * Welcome on the documentation for Timmi Absences API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developers@lucca.fr
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ImportsAbsenceBatchCreateResponseData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ImportsAbsenceBatchCreateResponse
 */
public class ImportsAbsenceBatchCreateResponseTest {
    private final ImportsAbsenceBatchCreateResponse model = new ImportsAbsenceBatchCreateResponse();

    /**
     * Model tests for ImportsAbsenceBatchCreateResponse
     */
    @Test
    public void testImportsAbsenceBatchCreateResponse() {
        // TODO: test ImportsAbsenceBatchCreateResponse
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

}
