/*
 * Timmi Absences API
 * Welcome on the documentation for Timmi Absences API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developers@lucca.fr
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ImportsEntitlementsBatchImportRequest
 */
public class ImportsEntitlementsBatchImportRequestTest {
    private final ImportsEntitlementsBatchImportRequest model = new ImportsEntitlementsBatchImportRequest();

    /**
     * Model tests for ImportsEntitlementsBatchImportRequest
     */
    @Test
    public void testImportsEntitlementsBatchImportRequest() {
        // TODO: test ImportsEntitlementsBatchImportRequest
    }

    /**
     * Test the property '_file'
     */
    @Test
    public void _fileTest() {
        // TODO: test _file
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'referenceDate'
     */
    @Test
    public void referenceDateTest() {
        // TODO: test referenceDate
    }

}
