/*
 * Timmi Absences API
 * Welcome on the documentation for Timmi Absences API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developers@lucca.fr
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ImportsAbsenceBatchCreateResponseDataReport;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ImportsAbsenceBatchCreateResponseData
 */
public class ImportsAbsenceBatchCreateResponseDataTest {
    private final ImportsAbsenceBatchCreateResponseData model = new ImportsAbsenceBatchCreateResponseData();

    /**
     * Model tests for ImportsAbsenceBatchCreateResponseData
     */
    @Test
    public void testImportsAbsenceBatchCreateResponseData() {
        // TODO: test ImportsAbsenceBatchCreateResponseData
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'report'
     */
    @Test
    public void reportTest() {
        // TODO: test report
    }

    /**
     * Test the property 'generatedAt'
     */
    @Test
    public void generatedAtTest() {
        // TODO: test generatedAt
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'lineTotal'
     */
    @Test
    public void lineTotalTest() {
        // TODO: test lineTotal
    }

    /**
     * Test the property 'testErrorTotal'
     */
    @Test
    public void testErrorTotalTest() {
        // TODO: test testErrorTotal
    }

    /**
     * Test the property 'totalStep'
     */
    @Test
    public void totalStepTest() {
        // TODO: test totalStep
    }

    /**
     * Test the property 'expectedCreationTotal'
     */
    @Test
    public void expectedCreationTotalTest() {
        // TODO: test expectedCreationTotal
    }

    /**
     * Test the property 'expectedUpdateTotal'
     */
    @Test
    public void expectedUpdateTotalTest() {
        // TODO: test expectedUpdateTotal
    }

    /**
     * Test the property 'testNonBlockingErrorTotal'
     */
    @Test
    public void testNonBlockingErrorTotalTest() {
        // TODO: test testNonBlockingErrorTotal
    }

    /**
     * Test the property 'currentStep'
     */
    @Test
    public void currentStepTest() {
        // TODO: test currentStep
    }

    /**
     * Test the property 'creationTotal'
     */
    @Test
    public void creationTotalTest() {
        // TODO: test creationTotal
    }

    /**
     * Test the property 'updateTotal'
     */
    @Test
    public void updateTotalTest() {
        // TODO: test updateTotal
    }

    /**
     * Test the property 'importErrorTotal'
     */
    @Test
    public void importErrorTotalTest() {
        // TODO: test importErrorTotal
    }

}
