/*
 * Timmi Absences API
 * Welcome on the documentation for Timmi Absences API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developers@lucca.fr
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Leave;
import com.konfigthis.client.model.LeavePeriodLog;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for LeavePeriod
 */
public class LeavePeriodTest {
    private final LeavePeriod model = new LeavePeriod();

    /**
     * Model tests for LeavePeriod
     */
    @Test
    public void testLeavePeriod() {
        // TODO: test LeavePeriod
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'ownerId'
     */
    @Test
    public void ownerIdTest() {
        // TODO: test ownerId
    }

    /**
     * Test the property 'isConfirmed'
     */
    @Test
    public void isConfirmedTest() {
        // TODO: test isConfirmed
    }

    /**
     * Test the property 'confirmationDate'
     */
    @Test
    public void confirmationDateTest() {
        // TODO: test confirmationDate
    }

    /**
     * Test the property 'attachmentId'
     */
    @Test
    public void attachmentIdTest() {
        // TODO: test attachmentId
    }

    /**
     * Test the property 'leaves'
     */
    @Test
    public void leavesTest() {
        // TODO: test leaves
    }

    /**
     * Test the property 'logs'
     */
    @Test
    public void logsTest() {
        // TODO: test logs
    }

}
