/*
 * Timmi Absences API
 * Welcome on the documentation for Timmi Absences API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developers@lucca.fr
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CancellationRequest;
import com.konfigthis.client.model.LeavePeriod;
import com.konfigthis.client.model.LeaveRequestApproval;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for LeaveRequest
 */
public class LeaveRequestTest {
    private final LeaveRequest model = new LeaveRequest();

    /**
     * Model tests for LeaveRequest
     */
    @Test
    public void testLeaveRequest() {
        // TODO: test LeaveRequest
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'leavePeriodId'
     */
    @Test
    public void leavePeriodIdTest() {
        // TODO: test leavePeriodId
    }

    /**
     * Test the property 'leavePeriod'
     */
    @Test
    public void leavePeriodTest() {
        // TODO: test leavePeriod
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'creationDate'
     */
    @Test
    public void creationDateTest() {
        // TODO: test creationDate
    }

    /**
     * Test the property 'nextApproverId'
     */
    @Test
    public void nextApproverIdTest() {
        // TODO: test nextApproverId
    }

    /**
     * Test the property 'cancellationUserId'
     */
    @Test
    public void cancellationUserIdTest() {
        // TODO: test cancellationUserId
    }

    /**
     * Test the property 'cancellationDate'
     */
    @Test
    public void cancellationDateTest() {
        // TODO: test cancellationDate
    }

    /**
     * Test the property 'isActive'
     */
    @Test
    public void isActiveTest() {
        // TODO: test isActive
    }

    /**
     * Test the property 'approvals'
     */
    @Test
    public void approvalsTest() {
        // TODO: test approvals
    }

    /**
     * Test the property 'cancellationRequests'
     */
    @Test
    public void cancellationRequestsTest() {
        // TODO: test cancellationRequests
    }

}
