/*
 * Timmi Absences API
 * Welcome on the documentation for Timmi Absences API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developers@lucca.fr
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.LeaveAccount;
import com.konfigthis.client.model.LeavePeriod;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Leave
 */
public class LeaveTest {
    private final Leave model = new Leave();

    /**
     * Model tests for Leave
     */
    @Test
    public void testLeave() {
        // TODO: test Leave
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'date'
     */
    @Test
    public void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'isAm'
     */
    @Test
    public void isAmTest() {
        // TODO: test isAm
    }

    /**
     * Test the property 'leaveAccountId'
     */
    @Test
    public void leaveAccountIdTest() {
        // TODO: test leaveAccountId
    }

    /**
     * Test the property 'leaveAccount'
     */
    @Test
    public void leaveAccountTest() {
        // TODO: test leaveAccount
    }

    /**
     * Test the property 'leavePeriodId'
     */
    @Test
    public void leavePeriodIdTest() {
        // TODO: test leavePeriodId
    }

    /**
     * Test the property 'leavePeriod'
     */
    @Test
    public void leavePeriodTest() {
        // TODO: test leavePeriod
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'creationDate'
     */
    @Test
    public void creationDateTest() {
        // TODO: test creationDate
    }

    /**
     * Test the property 'isActive'
     */
    @Test
    public void isActiveTest() {
        // TODO: test isActive
    }

    /**
     * Test the property 'cancellationDate'
     */
    @Test
    public void cancellationDateTest() {
        // TODO: test cancellationDate
    }

    /**
     * Test the property 'cancellationUserId'
     */
    @Test
    public void cancellationUserIdTest() {
        // TODO: test cancellationUserId
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

}
